run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - exportloopref
    - gochecknoinits
    - goconst
    - gocritic
    - gofmt
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wastedassign
    - nilerr
    - godot
    - godox
    - goimports
