package icons

// IconSubExt is a map to get the icon based on its subdirectory extension.
var IconSubExt = map[string]*IconInfo{
	"routing.ts":           IconSet["routing"],
	"routing.tsx":          IconSet["routing"],
	"routing.js":           IconSet["routing"],
	"routing.jsx":          IconSet["routing"],
	"routes.ts":            IconSet["routing"],
	"routes.tsx":           IconSet["routing"],
	"routes.js":            IconSet["routing"],
	"routes.jsx":           IconSet["routing"],
	"sln.dotsettings":      IconSet["settings"],
	"d.ts":                 IconSet["typescript-def"],
	"vcxitems.filters":     IconSet["visualstudio"],
	"vcxproj.filters":      IconSet["visualstudio"],
	"js.map":               IconSet["javascript-map"],
	"mjs.map":              IconSet["javascript-map"],
	"css.map":              IconSet["css-map"],
	"spec.ts":              IconSet["test-ts"],
	"e2e-spec.ts":          IconSet["test-ts"],
	"test.ts":              IconSet["test-ts"],
	"ts.snap":              IconSet["test-ts"],
	"spec.tsx":             IconSet["test-jsx"],
	"test.tsx":             IconSet["test-jsx"],
	"tsx.snap":             IconSet["test-jsx"],
	"spec.jsx":             IconSet["test-jsx"],
	"test.jsx":             IconSet["test-jsx"],
	"jsx.snap":             IconSet["test-jsx"],
	"spec.js":              IconSet["test-js"],
	"e2e-spec.js":          IconSet["test-js"],
	"test.js":              IconSet["test-js"],
	"js.snap":              IconSet["test-js"],
	"tf.json":              IconSet["terraform"],
	"blade.php":            IconSet["laravel"],
	"inky.php":             IconSet["laravel"],
	"gitlab-ci.yml":        IconSet["gitlab"],
	"stories.js":           IconSet["storybook"],
	"stories.jsx":          IconSet["storybook"],
	"story.js":             IconSet["storybook"],
	"story.jsx":            IconSet["storybook"],
	"stories.ts":           IconSet["storybook"],
	"stories.tsx":          IconSet["storybook"],
	"story.ts":             IconSet["storybook"],
	"story.tsx":            IconSet["storybook"],
	"azure-pipelines.yml":  IconSet["azure-pipelines"],
	"azure-pipelines.yaml": IconSet["azure-pipelines"],
}
